architecture: standalone

image:
  registry: docker.io
  repository: bitnamilegacy/postgresql
  tag: "16"

auth:
  enablePostgresUser: true
  database: openmetadata_db
  username: openmetadata_user
  password: openmetadata_password

primary:
  persistence:
    enabled: true
    storageClass: local-path
    size: 10Gi
  resources:
    requests:
      cpu: 200m
      memory: 256Mi
    limits:
      cpu: 1000m
      memory: 1024Mi
